server:
  port: 8888
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#mybatis:
#  mapperLocations: classpath:/mapper/*.xml
#  typeAliasesPackage: com.timayiedu.app.dao
#  mapperScanPackage: com.timayiedu.app.dao
#  configLocation: classpath:/mybatis-config.xml
#
#mysql:
#  datasource:
#    readSize: 2  #读库个数
#    type: com.alibaba.druid.pool.DruidDataSource
#    mapperLocations: classpath:/com/fei/springboot/dao/*.xml
#    configLocation: classpath:/mybatis-config.xml
#    write:
#      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&amp;characterEncoding=utf-8
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#      minIdle: 5
#      maxActive: 100
#      initialSize: 10
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 50
#      removeAbandoned: true
#      filters: stat
#    read01:
#      url: jdbc:mysql://127.0.0.1:3306/test_01?useUnicode=true&amp;characterEncoding=utf-8
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#      minIdle: 5
#      maxActive: 100
#      initialSize: 10
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 50
#      removeAbandoned: true
#      filters: stat
#    read02:
#      url: jdbc:mysql://127.0.0.1:3306/test_02?useUnicode=true&amp;characterEncoding=utf-8
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#      minIdle: 5
#      maxActive: 100
#      initialSize: 10
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 50
#      removeAbandoned: true
#      filters: stat